name = "roguelike"
main = "_worker.js"
compatibility_date = "2025-07-26"

[assets]
directory = "./dist"

[[routes]]
pattern = "roguelike.franzai.com/*"
zone_name = "franzai.com"

[env.preview]
name = "roguelike-preview"
routes = [
  { pattern = "preview.roguelike.franzai.com/*", zone_name = "franzai.com" }
]